name: Build latest images automatically

on:
    push:
        branches: ["main"]

jobs:
    deploy:
        strategy:
            fail-fast: false

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            # Build docker images
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: wh1isper
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push release
              id: docker_build_release_matrix
              uses: docker/build-push-action@v5
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64/v8
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  file: ./docker/Dockerfile
                  push: true
                  tags: wh1isper/redis-canal:dev
