name: Test example

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.10", "3.11", "3.12"]

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: "pip"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -e .[test]
            - name: Install all packages in example/extension
              run: |
                  python -m pip install -e example/extension/custom-adapter
            - name: Test with pytest
              run: |
                  pytest -vv example/extension
